### PR TITLE
Portuguese translation

### PR DESCRIPTION
**Pull request by kevinwsbr**

### CODE REVIEW

**Comment by Nicuz** [comment]
Hi Kevin, thank you very much for your help! I have a quick look at translation and I noticed that at line 40 you wrote "Tempo de forno", since it's very similair to italian I immediately thought it was a mistake. I checked with Google Translate and "forno" in portoguese is "oven" exactly as italian, however the string was "Fridge rising time" and it refers to the time that the dough stay to ferment in the fridge. Could you please check again your translation? Once it's correct I'll merge the PR! 😄

**Comment by Nicuz** [comment]
Hi Kevin, thank you very much for your help! I took a quick look at translation and I noticed that at line 40 you wrote "Tempo de forno", since it's very similair to italian I immediately thought it was a mistake. I checked with Google Translate and "forno" in portoguese is "oven" exactly as italian, however the string was "Fridge rising time" and it refers to the time that the dough stay to ferment in the fridge. Could you please check again your translation? Once it's correct I'll merge the PR! 😄

**Comment by Nicuz** [comment]
Hi Kevin, thank you very much for your help! I took a quick look to your translation and I noticed that at line 40 you wrote "Tempo de forno", since it's very similair to italian I immediately thought it was a mistake. I checked with Google Translate and "forno" in portoguese is "oven" exactly as italian, however the string was "Fridge rising time" and it refers to the time that the pizza dough stay to ferment in the fridge. Could you please check again your translation? Once it's correct I'll merge the PR! 😄

**Comment by kevinwsbr** [comment]
Exactly, I think it must have gone unnoticed at the time I was translating. Thanks for letting me know, I've already made the correction.

**Pull request merged**
